spring:
  profiles:
    include: default
  data:
    mongodb:
      host: mongo
  rabbitmq:
    host: rabbitmq

amqp:
  events:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true